import { useEffect, useState } from "react";
import { Bell, Building2, CalendarCheck2, ExternalLink, History, LayoutDashboard, MapPin, MessageSquare, Search, Trash2, UserRound, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import DashboardShell from "./DashboardShell.jsx";
import { getUserDashboard, removeSavedProperty } from "../../api/userApi.js";
import { useAuth } from "../../context/AuthContext.jsx";

const tabs = [["overview", "Overview", LayoutDashboard], ["saved", "Saved PGs", Building2], ["inquiries", "My Inquiries", MessageSquare], ["bookings", "Bookings / Requests", CalendarCheck2], ["searches", "Recent Searches", History], ["notifications", "Notifications", Bell], ["profile", "Profile", UserRound]];
function Notice({ notice, close }) { return notice && <div className={`fixed right-4 top-20 z-50 flex items-center gap-3 rounded-xl px-4 py-3 text-sm text-white shadow-xl ${notice.error ? "bg-red-600" : "bg-emerald-700"}`} role="status">{notice.message}<button onClick={close} aria-label="Close notification"><X size={16} /></button></div>; }
function Empty({ children }) { return <p className="rounded-lg border border-dashed border-primary/15 p-8 text-center text-sm text-primary/55">{children}</p>; }
function Status({ children }) { return <span className="rounded-full bg-primary/5 px-2.5 py-1 text-xs font-semibold text-primary">{children}</span>; }

export default function UserDashboard() {
  const { user, updateProfile } = useAuth();
  const navigate = useNavigate();
  const [tab, setTab] = useState("overview");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState(null);
  const [profile, setProfile] = useState({ name: user?.name || "", email: user?.email || "", phone: user?.phone || "" });
  const load = async () => { setLoading(true); setError(""); try { setData(await getUserDashboard()); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { setProfile({ name: user?.name || "", email: user?.email || "", phone: user?.phone || "" }); }, [user]);
  const action = async (operation, message) => { try { await operation(); await load(); setNotice({ message }); } catch (err) { setNotice({ message: err.message, error: true }); } };
  const saved = data?.savedProperties || [];
  const inquiries = data?.inquiries || [];
  const bookings = data?.bookings || [];
  const searches = data?.recentSearches || [];
  const notifications = data?.notifications || [];
  const title = (property) => property?.name || "Property removed";
  const content = () => {
    if (loading) return <div className="rounded-xl border border-primary/10 bg-white p-10 text-center text-sm text-primary/60">Loading your dashboard...</div>;
    if (error && !data) return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error}<button onClick={load} className="ml-4 rounded-lg bg-red-600 px-3 py-2 text-white">Retry</button></div>;
    if (tab === "overview") return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Saved PGs", data.stats.savedProperties, () => setTab("saved")], ["Recent searches", data.stats.recentSearches, () => setTab("searches")], ["Active inquiries", data.stats.activeInquiries, () => setTab("inquiries")], ["Bookings", data.stats.bookings, () => setTab("bookings")]].map(([label, value, onClick]) => <button key={label} onClick={onClick} className="w-full rounded-xl border border-primary/10 bg-white p-5 text-left shadow-sm"><p className="text-sm text-primary/60">{label}</p><p className="mt-2 text-3xl font-bold text-primary">{value}</p></button>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-primary/10 bg-white p-5"><h2 className="font-semibold text-primary">Recent activity</h2>{notifications.length ? <div className="mt-4 space-y-3">{notifications.slice(0, 4).map((item) => <div key={item.id} className="flex gap-3 rounded-lg bg-primary/5 p-3"><Bell size={16} className="mt-0.5 text-accent" /><div><p className="text-sm font-medium text-primary">{item.title}</p><p className="text-xs text-primary/60">{item.message}</p></div></div>)}</div> : <p className="mt-4 text-sm text-primary/60">No recent activity yet.</p>}</section><section className="rounded-xl bg-primary p-5 text-white"><p className="text-sm text-white/65">Quick actions</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><button onClick={() => navigate("/search")} className="rounded-lg bg-white/10 p-3 text-left text-sm font-semibold hover:bg-white/20"><Search size={16} className="mb-2" />Find PG</button><button onClick={() => navigate("/search")} className="rounded-lg bg-white/10 p-3 text-left text-sm font-semibold hover:bg-white/20"><MapPin size={16} className="mb-2" />Explore Area</button><button onClick={() => setTab("saved")} className="rounded-lg bg-white/10 p-3 text-left text-sm font-semibold hover:bg-white/20"><Building2 size={16} className="mb-2" />Saved PGs</button></div></section></div></>;
    if (tab === "saved") return <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold text-primary">Saved PGs</h2><p className="mt-1 text-sm text-primary/60">Your saved active properties.</p></div><button onClick={() => navigate("/search")} className="inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white"><Search size={15} /> Find PG</button></div>{saved.length ? <div className="grid gap-4 md:grid-cols-2">{saved.map((property) => <article key={property._id} className="rounded-xl border border-primary/10 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-primary">{title(property)}</h3><p className="mt-1 text-sm text-primary/60"><MapPin size={14} className="mr-1 inline" />{property.location}</p><p className="mt-2 text-sm text-primary/70">{property.rooms} rooms · {property.price}</p></div><Status>{property.status}</Status></div><div className="mt-4 flex gap-2"><button onClick={() => navigate(`/search?property=${property._id}`)} className="inline-flex items-center gap-1 rounded-lg border border-primary/15 px-3 py-2 text-sm font-semibold"><ExternalLink size={14} /> View</button><button onClick={() => action(() => removeSavedProperty(property._id), "PG removed from saved list.")} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600"><Trash2 size={14} /> Remove</button></div></article>)}</div> : <Empty>No saved PGs yet. Find a property and save it to see it here.</Empty>}</section>;
    if (tab === "inquiries") return <section><h2 className="text-xl font-semibold text-primary">My Inquiries</h2><p className="mt-1 text-sm text-primary/60">Messages sent to property owners.</p>{inquiries.length ? <div className="mt-5 space-y-3">{inquiries.map((item) => <div key={item._id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/10 bg-white p-4"><div><p className="font-semibold text-primary">{title(item.property)}</p><p className="text-sm text-primary/60">{new Date(item.createdAt).toLocaleDateString()} · {item.message}</p></div><Status>{item.status}</Status></div>)}</div> : <Empty>No inquiries sent yet.</Empty>}</section>;
    if (tab === "bookings") return <section><h2 className="text-xl font-semibold text-primary">My Bookings & Requests</h2><p className="mt-1 text-sm text-primary/60">Your booking request history and current status.</p>{bookings.length ? <div className="mt-5 space-y-3">{bookings.map((item) => <div key={item._id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/10 bg-white p-4"><div><p className="font-semibold text-primary">{title(item.property)}</p><p className="text-sm text-primary/60">Requested {new Date(item.createdAt).toLocaleDateString()}{item.moveInDate ? ` · Move in ${new Date(item.moveInDate).toLocaleDateString()}` : ""}</p></div><Status>{item.status}</Status></div>)}</div> : <Empty>No booking requests yet.</Empty>}</section>;
    if (tab === "searches") return <section><h2 className="text-xl font-semibold text-primary">Recent Searches</h2><p className="mt-1 text-sm text-primary/60">Repeat a search from your saved activity.</p>{searches.length ? <div className="mt-5 space-y-3">{searches.map((item, index) => <div key={`${item.createdAt}-${index}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/10 bg-white p-4"><div><p className="font-semibold text-primary">{item.query || "All PGs"}{item.location ? ` in ${item.location}` : ""}</p><p className="text-sm text-primary/60">{new Date(item.createdAt).toLocaleString()}</p></div><button onClick={() => navigate(`/search?q=${encodeURIComponent(item.query || "")}&location=${encodeURIComponent(item.location || "")}`)} className="inline-flex items-center gap-2 rounded-lg border border-primary/15 px-3 py-2 text-sm font-semibold"><History size={15} /> Repeat</button></div>)}</div> : <Empty>No recent searches yet.</Empty>}</section>;
    if (tab === "notifications") return <section><h2 className="text-xl font-semibold text-primary">Notifications</h2><p className="mt-1 text-sm text-primary/60">Updates from your inquiries and bookings.</p>{notifications.length ? <div className="mt-5 space-y-3">{notifications.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border border-primary/10 bg-white p-4"><Bell size={17} className="mt-0.5 text-accent" /><div><p className="font-semibold text-primary">{item.title}</p><p className="text-sm text-primary/60">{item.message} · {new Date(item.createdAt).toLocaleDateString()}</p></div></div>)}</div> : <Empty>No notifications yet.</Empty>}</section>;
    return <form onSubmit={(event) => { event.preventDefault(); action(() => updateProfile(profile), "Profile updated successfully."); }} className="max-w-xl space-y-4 rounded-xl border border-primary/10 bg-white p-5"><h2 className="text-xl font-semibold text-primary">Profile</h2><label className="block text-sm font-medium text-primary">Full name<input required value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} className="mt-2 w-full rounded-lg border border-primary/15 px-3 py-2.5" /></label><label className="block text-sm font-medium text-primary">Email<input required type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} className="mt-2 w-full rounded-lg border border-primary/15 px-3 py-2.5" /></label><label className="block text-sm font-medium text-primary">Phone<input required pattern="[0-9]{10}" value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} className="mt-2 w-full rounded-lg border border-primary/15 px-3 py-2.5" /></label><button className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-white">Save profile</button></form>;
  };
  return <DashboardShell roleLabel="User"><Notice notice={notice} close={() => setNotice(null)} /><div className="space-y-6"><div><p className="text-sm text-primary/60">Your workspace</p><h1 className="mt-1 text-2xl font-bold text-primary">Welcome, {user?.name}</h1><p className="mt-1 text-sm text-primary/60">{user?.email}</p></div><nav className="flex gap-1 overflow-x-auto border-b border-primary/10" aria-label="User dashboard tabs">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 text-sm font-medium ${tab === id ? "border-accent text-accent" : "border-transparent text-primary/60 hover:text-primary"}`}><Icon size={16} />{label}</button>)}</nav>{content()}</div></DashboardShell>;
}
