import { useEffect, useState } from "react";
import { Bell, Building2, CalendarCheck2, ExternalLink, History, LayoutDashboard, MapPin, MessageSquare, Search, Trash2, UserRound, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import DashboardShell from "./DashboardShell.jsx";
import { getUserDashboard, removeSavedProperty } from "../../api/userApi.js";
import { markAllNotificationsRead, markNotificationRead } from "../../api/notificationApi.js";
import { useAuth } from "../../context/AuthContext.jsx";

const tabs = [["overview", "Overview", LayoutDashboard], ["saved", "Saved PGs", Building2], ["inquiries", "My Inquiries", MessageSquare], ["bookings", "Bookings / Requests", CalendarCheck2], ["searches", "Recent Searches", History], ["notifications", "Notifications", Bell], ["profile", "Profile", UserRound]];
const statusTone = (status) => ["Confirmed", "Active", "Completed", "Replied"].includes(status) ? "bg-emerald-50 text-emerald-700" : ["Rejected", "Cancelled", "Closed"].includes(status) ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700";
const dateLabel = (value, withTime = false) => value ? new Date(value).toLocaleString(undefined, withTime ? { dateStyle: "medium", timeStyle: "short" } : { dateStyle: "medium" }) : "Date unavailable";
const rentLabel = (property) => typeof property?.monthlyRent === "number" ? `₹${property.monthlyRent.toLocaleString("en-IN")}` : property?.price || "Rent unavailable";
const roomLabel = { single: "Single Sharing", double: "Double Sharing", triple: "Triple Sharing", "4+": "4+ Sharing" };

function Notice({ notice, close }) { return notice && <div className={`fixed right-4 top-20 z-50 flex max-w-sm items-center gap-3 rounded-xl px-4 py-3 text-sm text-white shadow-xl ${notice.error ? "bg-red-600" : "bg-emerald-700"}`} role="status">{notice.message}<button onClick={close} aria-label="Close notification"><X size={16} /></button></div>; }
function Empty({ message, action, onAction }) { return <div className="rounded-xl border border-dashed border-primary/15 p-8 text-center text-sm text-primary/55"><p>{message}</p>{action && <button onClick={onAction} className="mt-4 rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white">{action}</button>}</div>; }
function Status({ children }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone(children)}`}>{children}</span>; }
function PropertyLink({ property, navigate }) { return property ? <button onClick={() => navigate(`/property/${property._id}`)} className="font-semibold text-primary hover:text-accent">{property.name}</button> : <span className="text-primary/55">This PG is no longer available.</span>; }

export default function UserDashboardImproved() {
  const { user, updateProfile } = useAuth();
  const navigate = useNavigate();
  const [tab, setTab] = useState("overview");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState(null);
  const [profile, setProfile] = useState({ name: user?.name || "", email: user?.email || "", phone: user?.phone || "" });
  const [profileSaving, setProfileSaving] = useState(false);

  const load = async () => { setLoading(true); setError(""); try { setData(await getUserDashboard()); } catch { setError("Unable to load your data. Please try again."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { setProfile({ name: user?.name || "", email: user?.email || "", phone: user?.phone || "" }); }, [user]);
  const action = async (operation, message) => { try { await operation(); await load(); setNotice({ message }); } catch { setNotice({ message: "Unable to complete that action. Please try again.", error: true }); } };
  const saved = data?.savedProperties || [];
  const inquiries = data?.inquiries || [];
  const bookings = data?.bookings || [];
  const searches = data?.recentSearches || [];
  const notifications = data?.notifications || [];
  const stats = data?.stats || {};

  const section = () => {
    if (tab === "overview") return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Saved PGs", stats.savedProperties ?? 0, "saved"], ["Active inquiries", stats.activeInquiries ?? 0, "inquiries"], ["Pending bookings", stats.pendingBookings ?? 0, "bookings"], ["Confirmed bookings", stats.confirmedBookings ?? 0, "bookings"], ["Unread notifications", stats.unreadNotifications ?? 0, "notifications"]].map(([label, value, destination]) => <button key={label} onClick={() => setTab(destination)} className="rounded-xl border border-primary/10 bg-white p-5 text-left shadow-sm"><p className="text-sm text-primary/60">{label}</p><p className="mt-2 text-3xl font-bold text-primary">{value}</p></button>)}</div><section className="mt-6 rounded-xl border border-primary/10 bg-white p-5"><h2 className="font-semibold text-primary">Recent notifications</h2>{notifications.length ? <div className="mt-4 space-y-3">{notifications.slice(0, 4).map((item) => <div key={item._id} className={`rounded-lg p-3 ${item.readAt ? "bg-primary/5" : "bg-amber-50"}`}><p className="text-sm font-medium text-primary">{item.title}</p><p className="mt-1 text-xs text-primary/60">{item.message} · {dateLabel(item.createdAt, true)}</p></div>)}</div> : <p className="mt-4 text-sm text-primary/60">You're all caught up.</p>}</section></>;
    if (tab === "saved") return <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold text-primary">Saved PGs</h2><p className="mt-1 text-sm text-primary/60">Properties you saved for later.</p></div><button onClick={() => navigate("/search")} className="inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white"><Search size={15} /> Find PG</button></div>{saved.length ? <div className="grid gap-4 md:grid-cols-2">{saved.map((property) => <article key={property._id} className="rounded-xl border border-primary/10 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><PropertyLink property={property} navigate={navigate} /><p className="mt-1 text-sm text-primary/60"><MapPin size={14} className="mr-1 inline" />{property.location || "Location unavailable"}</p><p className="mt-2 text-sm text-primary/70">{rentLabel(property)} · {roomLabel[property.roomType] || "Room type unavailable"}</p><p className="mt-1 text-sm text-primary/60">{typeof property.rating === "number" ? `⭐ ${property.rating.toFixed(1)}` : "No rating yet"} · {property.verificationStatus === "verified" ? "Verified" : "Unavailable"}</p></div><Status>{property.status || "Unavailable"}</Status></div><button onClick={() => action(() => removeSavedProperty(property._id), "PG removed from saved list.")} className="mt-4 inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600"><Trash2 size={14} /> Remove</button></article>)}</div> : <Empty message="You haven't saved any PGs yet." action="Find PG" onAction={() => navigate("/search")} />}</section>;
    if (tab === "inquiries") return <section><h2 className="text-xl font-semibold text-primary">My Inquiries</h2><p className="mt-1 text-sm text-primary/60">Messages sent to property owners.</p>{inquiries.length ? <div className="mt-5 space-y-3">{inquiries.map((item) => <article key={item._id} className="rounded-xl border border-primary/10 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><PropertyLink property={item.property} navigate={navigate} /><p className="mt-2 text-sm text-primary/70">{item.message}</p><p className="mt-2 text-xs text-primary/55">Sent {dateLabel(item.createdAt)}</p>{item.adminReply && <p className="mt-2 text-sm text-accent">Response: {item.adminReply}</p>}</div><Status>{item.status}</Status></div></article>)}</div> : <Empty message="You haven't sent any inquiries yet." action="Find a PG" onAction={() => navigate("/search")} />}</section>;
    if (tab === "bookings") return <section><h2 className="text-xl font-semibold text-primary">My Bookings & Requests</h2><p className="mt-1 text-sm text-primary/60">Your booking history and request status.</p>{bookings.length ? <div className="mt-5 space-y-3">{bookings.map((item) => <article key={item._id} className="rounded-xl border border-primary/10 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><PropertyLink property={item.property} navigate={navigate} /><p className="mt-2 text-sm text-primary/60">Requested {dateLabel(item.bookingDate || item.createdAt)}{item.moveInDate ? ` · Move in ${dateLabel(item.moveInDate)}` : ""}</p><p className="mt-1 text-sm text-primary/60">{item.property?.roomType ? roomLabel[item.property.roomType] : "Room information unavailable"}</p></div><Status>{item.status}</Status></div></article>)}</div> : <Empty message="You don't have any bookings yet." action="Find a PG" onAction={() => navigate("/search")} />}</section>;
    if (tab === "searches") return <section><h2 className="text-xl font-semibold text-primary">Recent Searches</h2>{searches.length ? <div className="mt-5 space-y-3">{searches.map((item, index) => <article key={`${item.createdAt}-${index}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/10 bg-white p-4"><div><p className="font-semibold text-primary">{item.query || "All PGs"}{item.location ? ` in ${item.location}` : ""}</p><p className="text-sm text-primary/60">{dateLabel(item.createdAt, true)}</p></div><button onClick={() => navigate(`/search?search=${encodeURIComponent(item.query || item.location || "")}`)} className="inline-flex items-center gap-2 rounded-lg border border-primary/15 px-3 py-2 text-sm font-semibold"><History size={15} /> Repeat</button></article>)}</div> : <Empty message="No recent searches yet." action="Find a PG" onAction={() => navigate("/search")} />}</section>;
    if (tab === "notifications") return <section><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-primary">Notifications</h2><p className="mt-1 text-sm text-primary/60">Updates about your activity.</p></div>{notifications.some((item) => !item.readAt) && <button onClick={() => action(markAllNotificationsRead, "All notifications marked as read.")} className="rounded-lg border border-primary/15 px-3 py-2 text-sm font-semibold">Mark all as read</button>}</div>{notifications.length ? <div className="mt-5 space-y-3">{notifications.map((item) => <article key={item._id} className={`flex gap-3 rounded-xl border p-4 ${item.readAt ? "border-primary/10 bg-white" : "border-amber-200 bg-amber-50"}`}><Bell size={17} className="mt-0.5 shrink-0 text-accent" /><div className="min-w-0 flex-1"><p className="font-semibold text-primary">{item.title}</p><p className="mt-1 text-sm text-primary/60">{item.message}</p><p className="mt-1 text-xs text-primary/50">{dateLabel(item.createdAt, true)}</p></div>{!item.readAt && <button onClick={() => action(() => markNotificationRead(item._id), "Notification marked as read.")} className="self-start text-xs font-semibold text-accent">Mark read</button>}</article>)}</div> : <Empty message="You're all caught up." />}</section>;
    return <form onSubmit={async (event) => { event.preventDefault(); if (!profile.name.trim() || !/^[0-9]{10}$/.test(profile.phone)) { setNotice({ message: "Enter a name and valid 10-digit phone number.", error: true }); return; } setProfileSaving(true); try { await updateProfile(profile); setNotice({ message: "Profile updated successfully." }); } catch { setNotice({ message: "Unable to update your profile. Please try again.", error: true }); } finally { setProfileSaving(false); } }} className="max-w-xl space-y-4 rounded-xl border border-primary/10 bg-white p-5"><h2 className="text-xl font-semibold text-primary">Profile</h2><label className="block text-sm font-medium text-primary">Full name<input required value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} className="mt-2 w-full rounded-lg border border-primary/15 px-3 py-2.5" /></label><label className="block text-sm font-medium text-primary">Email<input required type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} className="mt-2 w-full rounded-lg border border-primary/15 px-3 py-2.5" /></label><label className="block text-sm font-medium text-primary">Phone<input required pattern="[0-9]{10}" value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} className="mt-2 w-full rounded-lg border border-primary/15 px-3 py-2.5" /></label><button disabled={profileSaving} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{profileSaving ? "Saving..." : "Save profile"}</button></form>;
  };

  return <DashboardShell roleLabel="User"><Notice notice={notice} close={() => setNotice(null)} /><div className="space-y-6"><div><p className="text-sm text-primary/60">Your workspace</p><h1 className="mt-1 text-2xl font-bold text-primary">Welcome, {user?.name}</h1><p className="mt-1 text-sm text-primary/60">Manage saved PGs, inquiries, bookings, and notifications.</p></div><nav className="flex gap-1 overflow-x-auto border-b border-primary/10" aria-label="User dashboard tabs">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 text-sm font-medium ${tab === id ? "border-accent text-accent" : "border-transparent text-primary/60 hover:text-primary"}`}><Icon size={16} />{label}</button>)}</nav>{loading ? <div className="rounded-xl border border-primary/10 bg-white p-10 text-center text-sm text-primary/60">Loading your dashboard...</div> : error && !data ? <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error}<button onClick={load} className="ml-4 rounded-lg bg-red-600 px-3 py-2 text-white">Retry</button></div> : section()}</div></DashboardShell>;
}
